version: '3'

services:
    php:
        container_name: symfony-php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
    nginx:
        container_name: symfony-nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8002:80
        networks:
            - symfony
    redis:
        container_name: symfony-redis
        build:
           context: .
           dockerfile: docker/redis/Dockerfile
        networks:
            - symfony


volumes:
    db_app:

networks:
    symfony:
