version: '3'

services:
    php:
        container_name: symfony-php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./symfony/:/var/www/symfony/
        networks:
            - symfony
    nginx:
        container_name: symfony-nginx
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./symfony/:/var/www/symfony/
        ports:
            - 8002:80
        networks:
            - symfony
    mariadb:
        image: mariadb:10.4
        container_name: symfony-mariadb
        environment:
            MYSQL_ROOT_PASSWORD: changeme!
            MYSQL_DATABASE: mybb
            MYSQL_USER: mybb
            MYSQL_PASSWORD: changeme!
        ports:
            - 3306
        restart: 'always'
        volumes:
            - ./mariadb/mysql:/var/lib/mysql
            - ./mariadb/mariadb/conf:/etc/mysql
        networks:
            - symfony

    redis:
        container_name: symfony-redis
        build:
           context: .
           dockerfile: docker/redis/Dockerfile
        networks:
            - symfony


volumes:
    db_app:

networks:
    symfony:
